name: Docker Image CI

on:
  push:
    branches:
      - 'feature/**'
  pull_request:
    branches:
      - master
      - develop
      - 'feature/**'

jobs:
  # first: docker build job
  build:
    name: Build the Docker image
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build PHP image
      env:
        TZ: Asia/Tokyo
      run: docker build -t ${{ github.repository }}:${{ github.run_id }} --build-arg TZ=$TZ .
      working-directory: ./docker/php

  # second: docker push
