name: Docker Image CI

on:
  push:
    branches:
      - 'feature/**'
  pull_request:
    branches:
      - develop
      - 'feature/**'

jobs:
  # first: docker build job
  build:
    name: Build the Docker image
    runs-on: ubuntu-latest
    steps:
    - name: Buidl php image
      env:
        TZ: Asia/Tokyo
      run: docker build --no-cache --tag ${{ github.repository }}:${{ github.ref }} --build-arg TZ=$TZ ./docker/php
  # second: docker push
